### ISSUE TITLE
OSX TK depreciation warning

### ISSUE THREAD

**Issue by Erik-White** [Erik-White/ScanLag#16]
Since the latest update to OSX Catalina, a depreciation warning has been appearing for the system version of TK. Investigate the cause for this warning and determine if it can be avoided within the scope of ColonyScanalyser

> DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.

**Comment by zsqiang001** [comment]
Have you solve the problem? I don't know how to solve.

**Comment by Erik-White** [comment]
If you have set the rendering engine to TK e.g. `matplotlib.use("TkAgg")`, simply remove the line and rely on the default setting, or change to a different rendering engine.
