### ISSUE TITLE
Add plate names

### ISSUE THREAD

**Issue by vladimirg** [Erik-White/ScanLag#30]
Today, plates are identified as 1 through 6. It would be grand if they could be given a name, e.g. via a command-line flag.

**Comment by Erik-White** [comment]
I had considered this, but I felt that it would make the command line very verbose. I thought it would probably need a separate argument for each plate to ensure they were labelled correctly, so it seemed easier to just rename files afterwards.

But I suppose that renaming the files afterwards probably carries just as much of a risk of mix-ups as writing out a list of names in an argument. Maybe a single argument of comma separated values would work?
`--plate_names "plate_one, plate_two, plate_three"`

**Comment by vladimirg** [comment]
Yes, and in fact argparse already supports a list of items: https://docs.python.org/3/library/argparse.html#nargs

**Comment by Erik-White** [comment]
Ah, I already use `nargs`, but I didn't realise that it supports a list of arguments with undefined length!
