### ISSUE TITLE
--plate_labels "overshadows" path

### ISSUE THREAD

**Issue by vladimirg** [Erik-White/ScanLag#50]
The following command doesn't work:

> scanalyser --plate_labels "2062 SDC 1" "2062 SDC 2" "190 SDC 1" "190 SDC 2" "192 SDC 1" "192 SDC 2" Scanner0/

And gives the following output:
> usage: scanalyser [-h] [-dpi DOTS_PER_INCH] [-mp MULTIPROCESSING] [-p PLOTS]
>                   [--plate_edge_cut PLATE_EDGE_CUT]
>                   [--plate_labels [PLATE_LABELS [PLATE_LABELS ...]]]
>                   [--plate_lattice ROW COL] [--plate_size PLATE_SIZE]
>                   [--use_cached_data USE_CACHED_DATA] [-v VERBOSE]
>                   path
> scanalyser: error: the following arguments are required: path

However, if I insert --use_cached_data, it does:

> scanalyser --plate_labels "2062 SDC 1" "2062 SDC 2" "190 SDC 1" "190 SDC 2" "192 SDC 1" "192 SDC 2" --use_cached_data True Scanner0/

I'm guessing this happens because there's no "terminator" for the plate label list, and the last argument is interpreted as part of that list, as opposed to being independent.

**Comment by Erik-White** [comment]
This is occurring because the path must always the first argument, before any optional arguments.
See https://erik-white.github.io/ColonyScanalyser/command_line_arguments/

So it should work fine if you just rearrange it:
```
scanalyser Scanner0/ --plate_labels "2062 SDC 1" "2062 SDC 2" "190 SDC 1" "190 SDC 2" "192 SDC 1" "192 SDC 2"
```

**Comment by vladimirg** [comment]
I see - that's not obvious if I try to use the `--help` flag (and then `path` appears at the end).

**Comment by Erik-White** [comment]
I agree, argparse outputs the help with the `usage` section first which has the positional argument at the end of the list. [It looks like this behavious can be overriden](https://stackoverflow.com/questions/21185526/custom-usage-function-in-argparse), so I will see if I can add something more helpful
```
usage: scanalyser [-h] [-dpi DOTS_PER_INCH] [-mp MULTIPROCESSING] [-p PLOTS] [--plate_edge_cut PLATE_EDGE_CUT]
                  [--plate_labels [PLATE_LABELS [PLATE_LABELS ...]]] [--plate_lattice ROW COL] [--plate_size PLATE_SIZE]
                  [--use_cached_data USE_CACHED_DATA] [-v VERBOSE]
                  path
```

But then outputs a nice helpful list of the arguments in the correct order:
```
An image analysis tool for measuring microorganism colony growth

positional arguments:
  path                  Image files location

optional arguments:
  -h, --help            show this help message and exit
  -dpi DOTS_PER_INCH, --dots_per_inch DOTS_PER_INCH
                        The image DPI (dots per inch) setting (default: 300)
  -mp MULTIPROCESSING, --multiprocessing MULTIPROCESSING
                        Enables use of more CPU cores, faster but more resource intensive (default: True)
  -p PLOTS, --plots PLOTS
                        The detail level of plot images to store on disk (default: 1)
  --plate_edge_cut PLATE_EDGE_CUT
                        The exclusion area from the plate edge, as a percentage of the plate diameter (default: 5)
  --plate_labels [PLATE_LABELS [PLATE_LABELS ...]]
                        A list of labels to identify each plate. Plates are ordered from top left, in rows. Example usage:
                        --plate_labels plate1 plate2 (default: [])
  --plate_lattice ROW COL
                        The row and column co-ordinate layout of plates. Example usage: --plate_lattice 3 3 (default: (3, 2))
  --plate_size PLATE_SIZE
                        The plate diameter, in millimetres (default: 90)
  --use_cached_data USE_CACHED_DATA
                        Allow use of previously calculated data (default: False)
  -v VERBOSE, --verbose VERBOSE
                        Information output level (default: 1)
```
