### ISSUE TITLE
Multiprocessing ignores cores?

### ISSUE THREAD

**Issue by vladimirg** [Erik-White/ScanLag#51]
I have 1 CPU with 4 cores, which I'd like to use for Scanalyser. However, the default run (which should have MP enabled by default) does not seem to use this, as I see only one process active during analysis (and its CPU utilization is below 100%). It may also be a good idea to specify the number of cores/CPUs explicitly, for running on a cluster (where these parameters need to be requested explicitly from the cluster management software).

**Comment by Erik-White** [comment]
Can you provide some more details, operating system etc? A quick google shows some core affinity issues on Linux, but it's very hard to diagnose without more information

It _should_ be fully utilising 3 of the cores, as I see on my system:
<img width="496" alt="Screenshot 2020-06-01 at 17 32 12" src="https://user-images.githubusercontent.com/26148654/83421066-3272ef00-a430-11ea-93a4-e870e98ed14d.png">

I did a bit of research into Python on clusters, and appears that I'd probably have to rewrite the multiprocessing implementation which I'm not keen on but I'd consider it if there was enough demand for it.

**Comment by vladimirg** [comment]
I'm on macOS 10.13.6 (17G12034). I can show you when you visit the lab. I don't know what other details may be relevant (and I could be wrong in diagnosing the issue to begin with).

**Comment by Erik-White** [comment]
If you run the analysis with `--verbose 2`, what does the output say about the number of cores?

It should say something like:
```
Multiprocessing enabled, utilising 3 of 4 processors
```

**Comment by vladimirg** [comment]
The output is: `Multiprocessing enabled, utilising 7 of 8 processors`

At the processing images stage, I do see multiple processes spawned, but later on (calculating colony properties and detecting colonies) there's only one process.

The output is also strange, because I only have 1 processor and 4 cores (just checked via System Report).

**Comment by Erik-White** [comment]
Oh right, so it is working! It only uses multiprocessing for the slowest part, the image processing. I might see if I can extend it to the later stages, it can take a while if there's a lot of filtering to do.

The reason it is showing 8 cores is probably due to [hyperthreading](https://en.wikipedia.org/wiki/Hyper-threading). There's a nice [explanation on superuser](https://superuser.com/a/684009).

**Comment by vladimirg** [comment]
Cool, thanks. It did take quite a while to find the colonies for some of the plates (they ended up having ~150), so I think it's worthwhile the parallelize the rest as well.
