### ISSUE TITLE
False detection of colony

### ISSUE THREAD

**Issue by AlonaDeRusso** [Erik-White/ScanLag#64]
![plate_map - Copy](https://user-images.githubusercontent.com/66908246/84594110-a95cae80-ae58-11ea-8355-385ee50fc718.png)

plate 2, colony 135
Image locanion: Dropbox/Berman Lab Staff Files/Alona/Scanner3
Version: 0.4.4
while there was colony at the spot there was also false detection at the 30min mark.

[plate2_2062_SD_2_colony_timepoints.zip](https://github.com/Erik-White/ColonyScanalyser/files/4776430/plate2_2062_SD_2_colony_timepoints.zip)

**Comment by Erik-White** [comment]
Thanks for opening an issue Alona. I will have a look a the data and see if there is maybe some improvement I could make to the filtering.
