### ISSUE TITLE
 Issues with trend lines in growth_curve.png

### ISSUE THREAD

**Issue by AlonaDeRusso** [Erik-White/ScanLag#66]
![image](https://user-images.githubusercontent.com/66908246/84800037-de5a3400-b005-11ea-869f-acdc66e6f2d2.png)

Miscalculation of the real trends: lag time, carrying capacity, and maximum growth rate.
 
Plate Number: 3
Location in Dropbox: Berman Lab/Berman Lab Staff Files /Alona/ScanLag 28.5.20/Scanner3
Version: 0.4.4
 
[plate3_390_SD_1_colony_timepoints.zip](https://github.com/Erik-White/ColonyScanalyser/files/4787776/plate3_390_SD_1_colony_timepoints.zip)

**Comment by Erik-White** [comment]
This is the same kind of issue as #54 so I am going to close this one.
