### ISSUE TITLE
Trend lines are missing

### ISSUE THREAD

**Issue by AlonaDeRusso** [Erik-White/ScanLag#67]
![image](https://user-images.githubusercontent.com/66908246/84800716-de0e6880-b006-11ea-84f3-3d8093e74352.png)

Plate Number: 5
Location in Dropbox: Berman Lab/Berman Lab Staff Files /Alona/ScanLag 28.5.20/Scanner3
Version: 0.4.4
[plate5_390_SDC_1_colony_timepoints.zip](https://github.com/Erik-White/ColonyScanalyser/files/4787804/plate5_390_SDC_1_colony_timepoints.zip)

**Comment by Erik-White** [comment]
The curve fitting may not succeed if the data is not a good fit for the growth function, but this looks fine at a glance. I'm not sure why it was not able to fit the growth curve, I will have to look in to it.
