### ISSUE TITLE
Overlapping colonis

### ISSUE THREAD

**Issue by AlonaDeRusso** [Erik-White/ScanLag#69]
![image](https://user-images.githubusercontent.com/66908246/84802976-021f7900-b00a-11ea-906c-ebb5146acd5f.png)

When colonies overlap, not all colonies are measured.
How the overlap calculated in data plots? 

Plate Number: 6 
Location in Dropbox: Berman Lab/Berman Lab Staff Files /Alona/ScanLag 28.5.20/Scanner3
Version: 0.4.4

**Comment by Erik-White** [comment]
Colonies are measured until they merge so you see the colony area at the final measurement. Colonies are also filtered (see [filtering criteria](https://erik-white.github.io/ColonyScanalyser/colony_filtering/)) based on the number of data points etc. It is likely that some of these colonies merged quite early and did not have enough data points, so they were filtered out.
