### ISSUE TITLE
Unrecognized single colonies

### ISSUE THREAD

**Issue by AlonaDeRusso** [Erik-White/ScanLag#70]
plate 2
![image](https://user-images.githubusercontent.com/66908246/84805834-845d6c80-b00d-11ea-8422-cb70ba281c1d.png)

 plate 5
![image](https://user-images.githubusercontent.com/66908246/84805859-8fb09800-b00d-11ea-8bff-3f6a05aa9b58.png)

Location in Dropbox: Berman Lab/Berman Lab Staff Files /Alona/ScanLag 28.5.20/Scanner0
Version: 0.4.4

[plate_map.zip](https://github.com/Erik-White/ColonyScanalyser/files/4788095/plate_map.zip)

**Comment by Erik-White** [comment]
I will have a look at the data, but it is likely that these colonies were removed because they did meet the [colony filtering criteria](https://erik-white.github.io/ColonyScanalyser/colony_filtering/).

**Comment by AlonaDeRusso** [comment]
Thank you for your answers!
